#
# This Makefile was automatically generated by Code::Blocks IDE.
#

SRCS_f90d1 = \
mod_vector_algebra.f90 \
mod_cell_2D.f90 \
mod_write_vtk.f90 \
solver.f90 \
mod_detect_nearest_neighbor.f90 \
mod_struct_to_array.f90 \
mod_point_util.f90 \
mod_read_gmsh.f90 \
euler2d.f90 \
mod_fvm_face_2D.f90 \
mod_flux.f90 \
mod_solver.f90 \
pre_processing.f90 

OBJS_f90d1 = \
mod_vector_algebra.o \
mod_cell_2D.o \
mod_write_vtk.o \
solver.o \
mod_detect_nearest_neighbor.o \
mod_struct_to_array.o \
mod_point_util.o \
mod_read_gmsh.o \
euler2d.o \
mod_fvm_face_2D.o \
mod_flux.o \
mod_solver.o \
pre_processing.o 

SRC_DIR_f90d1 = 
OBJS_DIR = $(OBJS_f90d1)
EXE_DIR = 

EXE = euler2D
FC = gfortran
LD = gfortran
IDIR = 
CFLAGS = -ffree-line-length-none -g $(IDIR)
LFLAGS = 
LIBS = 

OBJS = $(OBJS_DIR)

all : $(EXE)

$(EXE) : $(OBJS_f90d1)
	$(LD) -o $(EXE_DIR)$(EXE) $(OBJS) $(LFLAGS) $(LIBS)

$(OBJS_f90d1):
	$(FC) $(CFLAGS) -c $(SRC_DIR_f90d1)$(@:.o=.f90)

clean :
	rm -f *.o *.mod
	rm -f $(EXE_DIR)$(EXE)

# Dependencies of files
mod_vector_algebra.o: \
    mod_vector_algebra.f90
mod_cell_2D.o: \
    mod_cell_2D.f90 \
    mod_point_util.o \
    mod_read_gmsh.o \
    mod_vector_algebra.o
mod_write_vtk.o: \
    mod_write_vtk.f90 \
    mod_cell_2D.o \
    mod_detect_nearest_neighbor.o \
    mod_read_gmsh.o \
    mod_solver.o
solver.o: \
    solver.f90 \
    mod_solver.o \
    mod_struct_to_array.o \
    mod_write_vtk.o
mod_detect_nearest_neighbor.o: \
    mod_detect_nearest_neighbor.f90 \
    mod_cell_2D.o \
    mod_read_gmsh.o
mod_struct_to_array.o: \
    mod_struct_to_array.f90 \
    mod_cell_2D.o \
    mod_fvm_face_2D.o
mod_point_util.o: \
    mod_point_util.f90 \
    mod_read_gmsh.o
mod_read_gmsh.o: \
    mod_read_gmsh.f90
euler2d.o: \
    euler2d.f90
mod_fvm_face_2D.o: \
    mod_fvm_face_2D.f90 \
    mod_cell_2D.o \
    mod_vector_algebra.o
mod_flux.o: \
    mod_flux.f90
mod_solver.o: \
    mod_solver.f90 \
    mod_cell_2D.o \
    mod_flux.o \
    mod_fvm_face_2D.o \
    mod_read_gmsh.o \
    mod_struct_to_array.o
pre_processing.o: \
    pre_processing.f90 \
    mod_cell_2D.o \
    mod_detect_nearest_neighbor.o \
    mod_fvm_face_2D.o \
    mod_read_gmsh.o \
    mod_write_vtk.o

